name: epub
version: 2.1.0
author: Colin Nelson <colin@orthros.dev>
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  async: ^2.5.0
  archive: ^3.1.2
  quiver: ^3.0.0
  xml: ^5.0.2
  image: ^3.0.2
dev_dependencies:
  test: ^1.16.8
  path: ^1.8.0
  pedantic: ^1.11.0
